### ISSUE TITLE
What do you think of Airflow so far?

### ISSUE THREAD

**Issue by julianpistorius** [researchapps/airflow-example#1]
Do you think it makes sense for research workflows?

We looked at it for use in CyVerse at one point, but I never played with it myself.

**Comment by vsoch** [comment]
I'm actually just experimenting with it myself - I added a pull request to add Singularity -> https://github.com/apache/airflow/pull/4846 and am awaiting further feedback (it looks like the testing failed, and oups, linting! I can fix that up) :)

I'm exploring it for using Singularity, because if it's easy to (already) use in more industry / cloud places, it might make sense to try integration with SLURM, for example. For a next step, I'd want to take a simple scientific pipeline and convert to airflow. I've read mixed things about its design, but I figure it doesn't hurt to try and prove them to myself.

**Comment by julianpistorius** [comment]
Sounds interesting. Thanks for sharing your impressions.

I'm interested in what you figure out, if you don't mind keeping this issue open and updating it with progress.

**Comment by vsoch** [comment]
Sure! But if you want to track progress, I think you should track the actual issue that is being worked on, https://github.com/apache/airflow/pull/4846 - this issue is more of a middleman to that. I'm going to close it here, and please subscribe to /follow the other issue.
